version: '3'

services:
  web_api:
    image: nginx:latest
    container_name: web_api
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./dev/nginx/conf.d/site.conf:/etc/nginx/conf.d/default.conf

  php_api:
    image: delirehberi/php7-symfony:7.1
    container_name: php_api
    volumes:
      - ./:/var/www

  db_api:
    image: mysql:5.7
    container_name: db_api
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=api
      - MYSQL_USER=chip
      - MYSQL_PASSWORD=ZF8WaFhf

  npm_api:
    image: catchdigital/node-sass:latest
    container_name: npm_api
    volumes:
      - ./:/var/www
  